### ISSUE TITLE
"Anykey" to fast-edit data does not work properly in date fields

### ISSUE THREAD

**Issue by nisensee** [thinwire/GridFastNavigation#6]
Although the anykey initiates the edit process for a date field, the typed value does not override the existing value like it is the case with the text field. Say I want to change the date to "24." ... something, than "2" triggers the edit mode, the new value is "4". If it was a text field, the value would be "24." ... something. Maybe the date field should behave similar to the other fields?

**Comment by thinwire** [comment]
Yeah, the date field should behave similar to the other fields - the problem is, that it doesn't, as it needs a server round-trip to complete before becoming editable. :)
First idea for improvement is to detect a datefield being targeted and, on keypress, buffer keypresses until the datefield is reliably in edit mode.

**Comment by thinwire** [comment]
This issue has been fixed in the latest architecture change.

**Comment by thinwire** [comment]
New version released.
